name: Acceptance Tests

on:
  pull_request:
    branches: [ 'master' ]

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: yarn start
