name: Acceptance Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  acceptance-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn start
