name: Auto Merge Minor Dependabot Updates

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge-minor-dependabot-updates:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.3
        with:
          github-token: "${{ secrets.DEPENDABOT_AUTO_MERGE_GITHUB_TOKEN }}"
      - name: Approve
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_AUTO_MERGE_GITHUB_TOKEN }}
      - name: Enable auto-merge
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_AUTO_MERGE_GITHUB_TOKEN }}
